export interface MenuItem {
  id: number;
  name: string;
  description: string;
  price: string;
  category: string;
  subcategory?: string;
  isVeg: boolean;
  image: string;
}

export const categories: string[] = [
  "All",
  "Starters",
  "Main Course",
  "Rice & Breads",
  "Beverages",
  "Desserts",
  "Thalis",
];

export const menuItems: MenuItem[] = [
  // ==================== STARTERS ====================
  {
    id: 1,
    name: "Fish Fry",
    description: "Crispy breadcrumb-coated Bekti fillet served with kasundi.",
    price: "₹320",
    category: "Starters",
    isVeg: false,
    image: "/menu/fish-fry.png",
  },
  {
    id: 2,
    name: "Chicken Pakora",
    description: "Golden fried chicken bites with Bengali spices.",
    price: "₹260",
    category: "Starters",
    isVeg: false,
    image: "/menu/default.png",
  },
  {
    id: 3,
    name: "Mochar Chop",
    description: "Banana blossom croquettes served with kasundi.",
    price: "₹180",
    category: "Starters",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 4,
    name: "Paneer Tikka",
    description: "Char-grilled paneer cubes with aromatic spices.",
    price: "₹290",
    category: "Starters",
    isVeg: true,
    image: "/menu/default.png",
  },

  // ==================== MAIN COURSE ====================
  {
    id: 5,
    name: "Moong Dal Koraishuti Diye",
    description:
      "Roasted green grams cooked in traditional Bengali style with ghee.",
    price: "₹160",
    category: "Main Course",
    subcategory: "Dal",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 6,
    name: "Machher Matha Diye Dal",
    description: "Yellow lentils cooked with fried fish head.",
    price: "₹210",
    category: "Main Course",
    subcategory: "Dal",
    isVeg: false,
    image: "/menu/default.png",
  },
  {
    id: 7,
    name: "Shukto",
    description: "Traditional Bengali mixed vegetables in creamy gravy.",
    price: "₹180",
    category: "Main Course",
    subcategory: "Veg",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 8,
    name: "Aloo Posto",
    description: "Potatoes cooked in rich poppy seed paste.",
    price: "₹190",
    category: "Main Course",
    subcategory: "Veg",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 9,
    name: "Dhokar Dalna",
    description: "Traditional lentil cakes in mildly spiced curry.",
    price: "₹220",
    category: "Main Course",
    subcategory: "Veg",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 10,
    name: "Elish Bhapa",
    description: "Hilsa steamed with mustard & poppy seed paste.",
    price: "₹450",
    category: "Main Course",
    subcategory: "Fish",
    isVeg: false,
    image: "/menu/default.png",
  },
  {
    id: 11,
    name: "Shorshe Ilish",
    description: "Hilsa cooked in traditional mustard gravy.",
    price: "₹480",
    category: "Main Course",
    subcategory: "Fish",
    isVeg: false,
    image: "/menu/default.png",
  },
  {
    id: 12,
    name: "Chingri Malai Curry",
    description: "King prawns cooked in creamy coconut gravy.",
    price: "₹520",
    category: "Main Course",
    subcategory: "Fish",
    isVeg: false,
    image: "/menu/default.png",
  },
  {
    id: 13,
    name: "Chicken Kosha",
    description: "Slow-cooked spicy Bengali chicken curry.",
    price: "₹360",
    category: "Main Course",
    subcategory: "Chicken",
    isVeg: false,
    image: "/menu/default.png",
  },
  {
    id: 14,
    name: "Chicken Chaap",
    description: "Rich Mughlai-style chicken in creamy gravy.",
    price: "₹390",
    category: "Main Course",
    subcategory: "Chicken",
    isVeg: false,
    image: "/menu/default.png",
  },
  {
    id: 15,
    name: "Kosha Mutton",
    description: "Classic slow-cooked Bengali mutton curry.",
    price: "₹420",
    category: "Main Course",
    subcategory: "Mutton",
    isVeg: false,
    image: "/menu/default.png",
  },
  {
    id: 16,
    name: "Mutton Rezala",
    description: "Royal Mughlai mutton cooked in yoghurt gravy.",
    price: "₹460",
    category: "Main Course",
    subcategory: "Mutton",
    isVeg: false,
    image: "/menu/default.png",
  },

  // ==================== RICE & BREADS ====================
  {
    id: 17,
    name: "Steamed Rice",
    description: "Premium steamed Gobindobhog rice.",
    price: "₹80",
    category: "Rice & Breads",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 18,
    name: "Basanti Pulao",
    description: "Sweet aromatic Bengali pulao with raisins & cashews.",
    price: "₹220",
    category: "Rice & Breads",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 19,
    name: "Butter Naan",
    description: "Soft tandoor-baked naan finished with butter.",
    price: "₹70",
    category: "Rice & Breads",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 20,
    name: "Laccha Paratha",
    description: "Layered flaky paratha served hot.",
    price: "₹80",
    category: "Rice & Breads",
    isVeg: true,
    image: "/menu/default.png",
  },

  // ==================== BEVERAGES ====================
  {
    id: 21,
    name: "Sweet Lassi",
    description: "Traditional chilled yogurt drink.",
    price: "₹120",
    category: "Beverages",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 22,
    name: "Fresh Lime Soda",
    description: "Refreshing sweet & salty lime soda.",
    price: "₹90",
    category: "Beverages",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 23,
    name: "Cold Coffee",
    description: "Creamy chilled coffee topped with ice cream.",
    price: "₹180",
    category: "Beverages",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 24,
    name: "Masala Chai",
    description: "Indian spiced milk tea.",
    price: "₹60",
    category: "Beverages",
    isVeg: true,
    image: "/menu/default.png",
  },

  // ==================== DESSERTS ====================
  {
    id: 25,
    name: "Mishti Doi",
    description: "Traditional caramelized sweet yogurt.",
    price: "₹120",
    category: "Desserts",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 26,
    name: "Rosogolla",
    description: "Soft spongy cottage cheese dumplings.",
    price: "₹100",
    category: "Desserts",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 27,
    name: "Baked Rosogolla",
    description: "Classic rosogolla baked with creamy topping.",
    price: "₹150",
    category: "Desserts",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 28,
    name: "Payesh",
    description: "Traditional Bengali rice pudding with cardamom.",
    price: "₹140",
    category: "Desserts",
    isVeg: true,
    image: "/menu/default.png",
  },

  // ==================== THALIS ====================
  {
    id: 29,
    name: "Veg Thali",
    description: "Rice, dal, vegetables, chutney & dessert.",
    price: "₹350",
    category: "Thalis",
    isVeg: true,
    image: "/menu/default.png",
  },
  {
    id: 30,
    name: "Fish Thali",
    description: "Rice, dal, fish curry, vegetables & dessert.",
    price: "₹520",
    category: "Thalis",
    isVeg: false,
    image: "/menu/default.png",
  },
  {
    id: 31,
    name: "Chicken Thali",
    description: "Rice, dal, chicken curry & dessert.",
    price: "₹480",
    category: "Thalis",
    isVeg: false,
    image: "/menu/default.png",
  },
  {
    id: 32,
    name: "Mutton Thali",
    description: "Complete Bengali mutton feast with dessert.",
    price: "₹650",
    category: "Thalis",
    isVeg: false,
    image: "/menu/default.png",
  },
];
